### PR TITLE
multiple outputs (no clobber)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

references:
- includes #25

changes (vs #25):
- [x] build wheels with `SPECIAL_MAGIC_ENV_VAR` to trigger crazy (maybe broken) `pdm` customization
- [x] clean up `ClobberWarnings` all over
- [x] use `noarch: generic` where possible

### CODE REVIEW

**Comment by bollwyvl** [comment]
@fcollonval not super _happy_ about what's going on in this, but it builds locally without warnings...

**Comment by bollwyvl** [comment]
@conda-forge/typer @conda-forge/typer-cli ready for review.

this would very probably fail if merged, and would need (as mentioned elsewhere)
- a PR to https://github.com/conda-forge/feedstock-outputs/ to "claim" `typer-cli`
- a PR to https://github.com/conda-forge/admin-requests to archive `typer-cli-feedstock`

**Comment by bollwyvl** [comment]
(also, @fcollonval happy to add you as maintainer, if so inclined)

**Comment by fcollonval** [comment]
Thanks a lot for the PR @bollwyvl 

> (also, @fcollonval happy to add you as maintainer, if so inclined)

Thanks for proposing. I can share the maintenance burden.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by fcollonval** [comment]
PR opened on admin-requests: https://github.com/conda-forge/admin-requests/pull/975

**Pull request merged**
