### PR TITLE
click 8.1.0 breaks typer 0.4.0

### PR DESCRIPTION
**Pull request by swails**
See tiangolo/typer#377 for more information

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by swails** [comment]
this pin is needed to avoid an `ImportError` on simply importing `typer` (typer is completely unusable with click 8.1.0)

**Comment by bollwyvl** [comment]
Thanks for the PR! 

Unfortunately, and frustratingly, adding a pin won't necessarily help much, as the solver is "greedy," and will simply select the older, still-incompatible version `_0`.

In the near term, we just have to deal with pinning versions (in this case, `click`).

The longer-term hope is for https://github.com/tiangolo/typer/pull/375 which would either preserve functionality with the existing range,

**Comment by bollwyvl** [comment]
#8 adds a click 8.1-compatible typer. Thanks again!

**Comment by tiangolo** [comment]
Hello! I just released Typer `0.4.1` that should handle this. :rocket: :nerd_face:

**Comment by bollwyvl** [comment]
@tiangolo thanks! we've already got [that version up](https://anaconda.org/conda-forge/typer/files?version=0.4.1) but still waiting for CDN for it to be widely distributed. :blush:

**Pull request closed without merging**
