### PR TITLE
typer 0.3.2, recipe updates, pip check, add maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes
- alternative to #3
- adds pins for dependencies
- adds pip check
- minor metadata updates
- adds self as maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/typer ready for review!

**Review by dfornika — APPROVED** [review]
Thanks @bollwyvl!

**Comment by dfornika** [comment]
@bollwyvl It's been a while since I merged an update for a conda package. On the [bioconda](https://github.com/bioconda/bioconda-recipes) project, there is a bot that can be called upon to perform the merge.

I checked the conda-forge docs but didn't find any instructions for merging. Can I just click the 'Merge pull request' button?

**Comment by bollwyvl** [comment]
Thanks for the speedy review!

Yeah, you can just push the big button... I don't see it in the [services docs](https://conda-forge.org/docs/maintainer/infrastructure.html#admin-web-services).

One _can_ add automerge, but I only feel comfortable with that when the tests are running under coverage with a (high) threshold. It's caused a bunch of problems, when "big" packages go and change stuff on point releases, etc. not caught by `pip check` or whatever.

The typer tests are in-dist, so that could be reasonable here, but I couldn't get the claimed :100: % (probably because windows), more like 83%.

**Pull request merged**
